code --install-extension bierner.color-info
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension golang.go
code --install-extension GregorBiswanger.json2ts
code --install-extension hbenl.vscode-mocha-test-adapter
code --install-extension hbenl.vscode-test-explorer
code --install-extension loiane.ts-extension-pack
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode.test-adapter-converter
code --install-extension naumovs.color-highlight
code --install-extension nowsci.glassit-linux
code --install-extension numso.prettier-standard-vscode
code --install-extension pmneo.tsimporter
code --install-extension QzSG.kitty-time
code --install-extension rbbit.typescript-hero
code --install-extension stringham.move-ts
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wmaurer.change-case
