code --install-extension 42crunch.vscode-openapi
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension bierner.color-info
code --install-extension bradlc.vscode-tailwindcss
code --install-extension bruce.rona
code --install-extension christian-kohler.path-intellisense
code --install-extension clemenspeters.format-json
code --install-extension cschlosser.doxdocgen
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-pull-request-github
code --install-extension goel.clone-pilot
code --install-extension golang.go
code --install-extension gregorbiswanger.json2ts
code --install-extension hbenl.vscode-mocha-test-adapter
code --install-extension hbenl.vscode-test-explorer
code --install-extension hogashi.vscode-copy-github-permalink
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jock.svg
code --install-extension josetr.cmake-language-support-vscode
code --install-extension kavod-io.vscode-jest-test-adapter
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension loiane.ts-extension-pack
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.debugpy
code --install-extension ms-python.flake8
code --install-extension ms-python.isort
code --install-extension ms-python.pylint
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension naumovs.color-highlight
code --install-extension orta.vscode-jest
code --install-extension pmneo.tsimporter
code --install-extension qzsg.kitty-time
code --install-extension redhat.vscode-yaml
code --install-extension stringham.move-ts
code --install-extension styled-components.vscode-styled-components
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension wmaurer.change-case
code --install-extension zixuanchen.vitest-explorer
