code --install-extension bierner.color-info
code --install-extension Bruce.rona
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cschlosser.doxdocgen
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension GitHub.copilot
code --install-extension GitHub.vscode-pull-request-github
code --install-extension Goel.clone-pilot
code --install-extension golang.go
code --install-extension GregorBiswanger.json2ts
code --install-extension hbenl.vscode-test-explorer
code --install-extension jeff-hykin.better-cpp-syntax
code --install-extension jock.svg
code --install-extension kavod-io.vscode-jest-test-adapter
code --install-extension loiane.ts-extension-pack
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension naumovs.color-highlight
code --install-extension nowsci.glassit-linux
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension pmneo.tsimporter
code --install-extension QzSG.kitty-time
code --install-extension rbbit.typescript-hero
code --install-extension steoates.autoimport
code --install-extension stringham.move-ts
code --install-extension twxs.cmake
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wmaurer.change-case
