on: [push]

jobs:
  smoke_test:
    runs-on: ubuntu-latest
    name: Smoke Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run smoke
        uses: ./ # Uses an action in the root directory
        id: hello
